layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

timezone: Australia/West

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  sort_by options:
    - pushed
    # - stars
  limit: 6
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: lam.ngoctam.1
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: ngoctamlam
  # mastodon: your_username
  medium: amngoctam
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  website: http://lamngoctam.github.io
  # youtube: your_username
  github: lamngoctam

# Me!
topics:
  - name: Higher degree by research - Curtin University
    web_url: https://study.curtin.edu.au/higher-degree-by-research/
    image_url: /assets/images/company/curtin.jpg

  - name: Biorobotics Research Lab - Curtin University
    web_url: https://scieng.curtin.edu.au/research/biorobotics-research-lab/
    image_url: /assets/images/company/curtin.jpg

  - name: VinAi Research - Pushing the frontier of Artificial Intelligence
    web_url: https://www.vinai.io
    image_url: /assets/images/company/vinai.png

old-roles:
  - name: Nexxis Software Engineer Intern
    web_url: https://nexxis.com.au
    image_url: /assets/images/company/nexxis.png

  - name: Innovation Center Perth Software Engineer Intern
    web_url: https://icentralau.com.au/Perth/
    image_url: /assets/images/company/icp.jpg

  - name: Autonomous RC Excavator
    web_url: https://www.youtube.com/
    image_url: /assets/images/company/excavator.jpg

# portfolio topics
pitems:
  - name: Mesh Legolizer Maya Plugin
    description: C++, Python, MEL
    web_url: https://github.com/lamngoctam
    image_url: /images/project_gifs/
  
  - name: MPM Simulations 
    description: C++, Houdini
    web_url: /pages/mpm-simulations
    image_url: /images/project_gifs/

  - name: Monte Carlo Pathtracer
    description: C++
    web_url: /pages/monte-carlo
    image_url: /images/

  - name: 3D Mesh Editor
    description: C++, OpenGL
    web_url: /pages/mesh-editor
    image_url: /images/project_gifs/

  - name: UAV
    description: C++, OpenGL
    web_url: /pages/demo-reel
    image_url: /images/project_gifs

  - name: Shaders
    description: C++, OpenGL
    web_url: /pages/shaders
    image_url: /images/project_gifs/wahoo.gif

  - name: Volunteer Management App
    description: React, Django
    web_url: https://github.com/lamngoctam
    image_url: /images/project_gifs/

  - name: WeathAR
    description: C#, Unity
    web_url: https://github.com/lamngoctam
    image_url: /images/

  - name: Waveform Segmentation
    description: Python, Keras
    web_url: https://github.com/lamngoctam
    image_url: /images/
